"""Add institution field to User model

Revision ID: 06db884c896c
Revises: a0c182a3e3b9
Create Date: 2025-10-13 22:38:28.034697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06db884c896c'
down_revision = 'a0c182a3e3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('institution')

    # ### end Alembic commands ###
