"""Add score to ExerciseSubmission

Revision ID: 2dc1df42c73f
Revises: 444ee8d13646
Create Date: 2025-10-14 05:01:52.331771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc1df42c73f'
down_revision = '444ee8d13646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_submission', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
