"""Add meeting_url to Lesson model

Revision ID: 3177a3d77f7e
Revises: 6f2f0b3365ce
Create Date: 2025-10-13 23:35:58.205075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3177a3d77f7e'
down_revision = '6f2f0b3365ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('meeting_url')

    # ### end Alembic commands ###
