"""Add ExerciseSubmission model

Revision ID: 444ee8d13646
Revises: f9b0f5a5a556
Create Date: 2025-10-14 00:18:42.639797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444ee8d13646'
down_revision = 'f9b0f5a5a556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('submission_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_exercise_submission_user_course')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_submission')
    # ### end Alembic commands ###
