"""Add material_type to Course model

Revision ID: 6f2f0b3365ce
Revises: c07ea1c2e407
Create Date: 2025-10-13 22:50:13.082214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2f0b3365ce'
down_revision = 'c07ea1c2e407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('material_type')

    # ### end Alembic commands ###
