"""Add certificate fields to User model

Revision ID: 70e705ace1ea
Revises: 2dc1df42c73f
Create Date: 2025-10-14 12:18:29.689753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e705ace1ea'
down_revision = '2dc1df42c73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('certificate_data', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('certificate_data')
        batch_op.drop_column('certificate_type')

    # ### end Alembic commands ###
