"""Add start_date to Lesson model

Revision ID: 984520018949
Revises: a951f29987e8
Create Date: 2025-10-21 09:17:56.746592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984520018949'
down_revision = 'a951f29987e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
