"""Add expertise field to User model

Revision ID: a0c182a3e3b9
Revises: 7b80e89b91f9
Create Date: 2025-10-13 22:32:53.924315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c182a3e3b9'
down_revision = '7b80e89b91f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expertise', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('expertise')

    # ### end Alembic commands ###
