"""Add quiz start and end date to Course model

Revision ID: a951f29987e8
Revises: 39d640825b80
Create Date: 2025-10-21 04:35:26.456152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a951f29987e8'
down_revision = '39d640825b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('quiz_end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('quiz_end_date')
        batch_op.drop_column('quiz_start_date')

    # ### end Alembic commands ###
