"""Add teaching_experience field to User model

Revision ID: c07ea1c2e407
Revises: 06db884c896c
Create Date: 2025-10-13 22:41:30.164223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07ea1c2e407'
down_revision = '06db884c896c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teaching_experience', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('teaching_experience')

    # ### end Alembic commands ###
